version: "3"
services:
  docker-postgres:
    container_name: local_telephony_postgresql
    image: postgres:15.3-alpine
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - docker/env/postgresql.env

  docker-mongodb:
    container_name: local_telephony_mongodb
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    env_file:
      - docker/env/mongodb.env

  telephony-app:
    depends_on:
      - docker-postgres
      - docker-mongodb
    build:
      context: .
    container_name: telephony-app
    environment:
      - POSTGRES_HOST=local_telephony_postgresql
      - MONGODB_HOST=local_telephony_mongodb
    ports:
      - "8099:8099"
