version: "3"
services:
  docker-postgres:
    container_name: local_telephony_postgresql
    image: postgres:15.3-alpine
    restart: always
    expose:
      - 5432
    ports:
      - "5438:5432"
    env_file:
      - docker/env/postgresql.env
    volumes:
      - ./dbdata/mongodb:/data/db
  
  docker-mongodb:
    container_name: local_telephony_mongodb
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - "27039:27017"
    env_file:
      - docker/env/mongodb.env
    volumes:
      - ./dbdata/mongodb:/data/db