spring:
  application:
    name: telephony-test-task-demo
  main:
    banner-mode: off
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: local_pg_user
    password: y0ONKIOdCaj2n23
    maximumPoolSize: 30
    minimumIdle: 5
    dataSourceProperties:
      serverName: localhost
      portNumber: 5438
      databaseName: local_telephony_posgresql
    flyway:
      enabled: true
      locations: "classpath:db/migration"


mybatis:
  mapper-locations: "classpath:db/mappers/*.xml"
  config-location: "classpath:mybatis-config.xml"

server:
  port: 8091
