spring:
  application:
    name: telephony
  main:
    banner-mode: off
  data:
    mongodb:
      username: local_mongo_user
      password: 106fe2e9be0e4016a60f68ad40c9451a
      host: ${MONGODB_HOST}
      port: 27017
      database: telephony
      authentication-database: admin
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: local_pg_user
    password: y0ONKIOdCaj2n23
    maximumPoolSize: 30
    minimumIdle: 5
    dataSourceProperties:
      serverName: ${POSTGRES_HOST}
      portNumber: 5432
      databaseName: local_telephony_posgresql
    flyway:
      enabled: true
      locations: "classpath:db/migration"


mybatis:
  mapper-locations: "classpath:db/mappers/*.xml"
  config-location: "classpath:mybatis-config.xml"

mongock:
  change-logs-scan-package: "kz.arabro.telephony.util.migration"

server:
  port: 8099
