spring:
  application:
    name: telephony-test-task-demo
  main:
    banner-mode: off
  data:
    mongodb:
      username: local_mongo_user
      password: 106fe2e9be0e4016a60f68ad40c9451a
      host: localhost
      port: 27039
      database: telephony
      authentication-database: admin
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    username: local_pg_user
    password: y0ONKIOdCaj2n23
    maximumPoolSize: 30
    minimumIdle: 5
    dataSourceProperties:
      serverName: localhost
      portNumber: 5438
      databaseName: local_telephony_posgresql
    flyway:
      enabled: true
      locations: "classpath:db/migration"


mybatis:
  mapper-locations: "classpath:db/mappers/*.xml"
  config-location: "classpath:mybatis-config.xml"

mongock:
  change-logs-scan-package: "kz.arabro.telephony.util.migration"

server:
  port: 8091
